import { EmbedBuilder } from 'discord.js';
import config from '../config.js';
import logger from '../utils/logger.js';
import { getTestChannels } from '../utils/testChannels.js';
import rateLimit from '../utils/rateLimit.js';
import { canBotManageMessages } from '../utils/permissions.js';

export const command = {
  name: 'syedlink',
  description: 'Post the server invite to test channels',
  async execute(message) {
    const userId = message.author.id;
    const guildId = message.guild.id;

    try {
      const testChannels = await getTestChannels(message.guild);

      if (testChannels.size === 0) {
        logger.logOperation(userId, guildId, 'syedlink', 'NO_CHANNELS', 'No test channels found');
        return message.reply('❌ No test channels found.');
      }

      const embed = new EmbedBuilder()
        .setColor('#0099FF')
        .setTitle('📢 SERVER TEST INVITE')
        .setDescription(`${config.serverInviteUrl}`)
        .setFooter({ text: 'This is a test message generated by SYEDNUKE' })
        .setTimestamp();

      let successCount = 0;
      let failedCount = 0;
      const errors = [];

      logger.info(`📢 Posting invite to ${testChannels.size} test channels...`);

      for (const channel of testChannels.values()) {
        try {
          if (!canBotManageMessages(channel, message.guild.members.me)) {
            failedCount++;
            errors.push({
              channel: channel.name,
              error: 'No permission to send messages',
            });
            continue;
          }

          await rateLimit.wait(`channel-${channel.id}`);
          await channel.send({ embeds: [embed] });
          successCount++;
          logger.info(`✅ Posted invite to ${channel.name}`);
        } catch (error) {
          failedCount++;
          errors.push({
            channel: channel.name,
            error: error.message,
          });
          logger.error(`Failed to post to ${channel.name}: ${error.message}`);
        }
      }

      const resultEmbed = new EmbedBuilder()
        .setColor(failedCount === 0 ? '#00FF00' : '#FFFF00')
        .setTitle('✅ INVITE POSTING COMPLETE')
        .addFields(
          { name: 'Successful', value: `${successCount}`, inline: true },
          { name: 'Failed', value: `${failedCount}`, inline: true },
          { name: 'Total', value: `${testChannels.size}`, inline: true }
        )
        .setFooter({ text: 'Invite posting operation complete' })
        .setTimestamp();

      logger.logOperation(userId, guildId, 'syedlink', 'SUCCESS', `Posted to ${successCount} channels, ${failedCount} failed`);
      return message.reply({ embeds: [resultEmbed] });
    } catch (error) {
      logger.error(`syedlink command error: ${error.message}`);
      logger.logOperation(userId, guildId, 'syedlink', 'ERROR', error.message);
      return message.reply('❌ An error occurred. Check logs for details.');
    }
  },
};
